name: Assignment 5 ML Pipeline

on:
  push:
    branches-ignore:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      force_accuracy:
        description: "Optional accuracy override for demo runs (e.g., 0.80 or 0.90)"
        required: false
        default: ""

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assignment 5
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_EXPERIMENT_NAME: assignment5_pipeline
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn dvc

      - name: Pull dataset with DVC
        run: dvc pull

      - name: Train model and log to MLflow
        env:
          FORCE_ACCURACY: ${{ github.event.inputs.force_accuracy }}
        run: python train.py

      - name: Upload model info
        uses: actions/upload-artifact@v5
        with:
          name: model-info
          path: assignment 5/model_info.txt

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    defaults:
      run:
        working-directory: assignment 5
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      - name: Download model info artifact
        uses: actions/download-artifact@v5
        with:
          name: model-info
          path: assignment 5

      - name: Check accuracy threshold
        run: python check_threshold.py

      - name: Mock build docker image
        run: echo "Building Docker image for Run ID: $(cat model_info.txt)"
